"""目标 SQL Server 运行时组件部署 SQL"""

RUNTIME_SQL = """
-- 1. 创建 EXECUTION_LOG 表（如不存在）
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EXECUTION_LOG')
BEGIN
    CREATE TABLE [dbo].[EXECUTION_LOG] (
        [ID] INT IDENTITY(1,1) PRIMARY KEY,
        [LOG_SOURCE] NVARCHAR(255) NULL,
        [LOG_TYPE] CHAR(1) DEFAULT 'N',
        [MESSAGE] NVARCHAR(MAX) NULL,
        [CREATED_AT] DATETIME DEFAULT GETDATE()
    )
END
GO

-- 2. USP_WRITELOG 存储过程
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'USP_WRITELOG')
    DROP PROCEDURE [dbo].[USP_WRITELOG]
GO

CREATE PROCEDURE [dbo].[USP_WRITELOG]
    @MESSAGE NVARCHAR(MAX),
    @LOG_SOURCE NVARCHAR(255) = NULL,
    @LOG_TYPE CHAR(1) = 'N'
AS
BEGIN
    SET NOCOUNT ON
    INSERT INTO [dbo].[EXECUTION_LOG] ([LOG_SOURCE], [LOG_TYPE], [MESSAGE], [CREATED_AT])
    VALUES (@LOG_SOURCE, @LOG_TYPE, @MESSAGE, GETDATE())
END
GO
"""